#!/bin/sh

# This script will install just the essential packages to build
# the standalone executable (not the rofi mode)

# A very minimal environment might not contain sudo
if ! command -V sudo; then
  apt-get update
  apt-get install -y --no-install-recommends sudo
fi
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  build-essential pkg-config libsqlite3-dev
